### PR TITLE
Correct segment index.

### PR DESCRIPTION
**Pull request by fdb**
When encoding multiple letters, the segments seem to shift, which I think is caused by an off-by-one error in addSegment. I've applied the fix in my code and it seems to work -- code segments align correctly with the glyphs.

Since you're only encoding one glyph it might be that you've never encountered the issue. Or I might be completely wrong :-)

Note that I've only tested this with cmap format 4 -- other formats might cause different issues.

### CODE REVIEW

**Comment by Pomax** [comment]
hm, are you sure the fix should be in the `idx`, rather than in the segment delta? (I thought the idx computation was correct in that it'd end up being the correct glyphid, but I'll have to find some time tomorrow to look at it anew =)

**Comment by fdb** [comment]
Frankly, I have no idea. At least in the case of opentype.js, there is an off-by-one error, but I'm not familiar enough with the `cmap` table to know where it is.

**Comment by Pomax** [comment]
based on what the code I'm using is doing, this is definitely correct behaviour. What you want to do instead of make sure the `delta` value always sets up a continuous sequence, so that previous(end) + previous(delta) + 1 == current(start) + current(delta). The `start` and `end` values give the segment's "true" start and end character codes, and the `delta` for each segment ensures that when you generate the delta-corrected sequence for all segments, you get the sequence 1, 2, 3, ..... etc.

So in this case, the code is actually doing exactly what it needs to do, but ported to a "lots of normal character" situation probably requires you to get the delta values correct. The documentation on the [cmap subtable format 4](http://www.microsoft.com/typography/OTSPEC/cmap.htm) will probably help explain this a bit more (scroll down to the `Format 4: Segment mapping to delta values` section)

**Comment by fdb** [comment]
Okay -- I'll look into it more for opentype.js. Again, `cmap`s are definitely not my area of expertise. Thanks for the explanation!

**Comment by Pomax** [comment]
I found reading through the cmap documentation to be pretty useful, if a little "opentype speccy". The information's there, but sometimes a little terse.

**Pull request closed without merging**
