### PR TITLE
Make build step more explicit

### PR DESCRIPTION
**Pull request by eric-brechemier**
I had trouble running the build by following instructions in the README.

I simplified the build by installing requirejs locally and updated the instructions to run the build successfully.

Kudos to http://stackoverflow.com/a/24417867 for the `npm bin` trick.

### CODE REVIEW

**Comment by Pomax** [comment]
hm, but on windows all the "xyz" commands are just "xyz.cmd", so `r.js` becomes `r.js.cmd` and done. We shouldn't need a local node_modules dir there.

That said, I should probably redo this as a plain commonjs format instead, and use a browserify build process instead. Easier to maintain and test that way, too.

**Comment by eric-brechemier** [comment]
To be honest, I simplified the build _for me_ because for some reason, `sudo npm install -g` fails in my current setup :) and I thought that it simplified _the explanation_ because the path for Windows could be relative instead of absolute.

Still, with only a mention of RequireJS in passing, these instructions need some clarification. I also had to update the parameter, from `build` to `build.js`.

Perhaps we could add a paragraph that indicates that RequireJS is a prerequisite; that it can be installed locally or globally; and that in both cases, the build can be run with the command:

``` sh
r.js -o build.js
```

given that you configure the path in a way that allows to find r.js.

Any thoughts?

**Comment by eric-brechemier** [comment]
Or `r.js` could be included in the repository, like `require.js` is included already.

According to [RequireJS docs](http://requirejs.org/docs/node.html), this has the following impact on the code:

> These instructions assume an npm installation of 'requirejs'. If you are using the r.js file directly, replace require('requirejs') with require('./path/to/r.js').

**Comment by Pomax** [comment]
hm. it's probably more productive to convert the code to commonjs format instead here. It's relatively straight forward changes, mostly changing the defines to `module.exports` and inlining the requires instead of resolving them off of string arrays.

**Comment by eric-brechemier** [comment]
OK, your call :)

**Comment by Pomax** [comment]
I should be able to do this on Thursday. Now if only github had reminders...

**Pull request closed without merging**
